### ISSUE TITLE
Where’s my place?

### ISSUE THREAD

**Issue by walkerljy** [ljy-002/Web-gitignore.github.io#57]
Hey, could you please add my name to your “friend” list?
呵呵😄
“I asked shamelessly”

By Michael Liu

**Comment by ljy-002** [comment]
Yes, but you need to have a web page

**Comment by ljy-002** [comment]
And have more than 3 accounts across the country

**Comment by ljy-002** [comment]
我把你加上了，你说一下你的·Scratch账号网址
